/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trail;

import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.Semaphore;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author danx_
 */
public class Trail extends javax.swing.JFrame {

    /**
     * Creates new form Trail
     */
    public Trail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        train2 = new javax.swing.JLabel();
        train1 = new javax.swing.JLabel();
        train3 = new javax.swing.JLabel();
        track1 = new javax.swing.JLabel();
        track2 = new javax.swing.JLabel();
        track3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg = new javax.swing.JTextArea();
        buttonStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(200, 100));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 600));

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 600));
        jPanel1.setLayout(null);

        train2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trail/Train2.png"))); // NOI18N
        train2.setAlignmentY(0.0F);
        jPanel1.add(train2);
        train2.setBounds(1150, 410, 100, 100);

        train1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trail/Train1.png"))); // NOI18N
        train1.setAlignmentY(0.0F);
        jPanel1.add(train1);
        train1.setBounds(50, 410, 100, 100);

        train3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trail/train3.png"))); // NOI18N
        jPanel1.add(train3);
        train3.setBounds(600, 500, 100, 100);

        track1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trail/TrainTrack.png"))); // NOI18N
        track1.setAlignmentY(0.0F);
        track1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(track1);
        track1.setBounds(50, 50, 600, 460);

        track2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trail/TrainTrack.png"))); // NOI18N
        track2.setAlignmentY(0.0F);
        track2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(track2);
        track2.setBounds(650, 50, 600, 460);

        track3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trail/TrainTrackStraigth.png"))); // NOI18N
        jPanel1.add(track3);
        track3.setBounds(600, 0, 100, 600);

        msg.setColumns(20);
        msg.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        msg.setRows(5);
        jScrollPane1.setViewportView(msg);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(720, 510, 580, 106);

        buttonStart.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        buttonStart.setText("Go!");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });
        jPanel1.add(buttonStart);
        buttonStart.setBounds(200, 530, 100, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Runnable resetTrains = new Runnable() {
        public void run() {
            System.out.println("Starting again");
        }
    };

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        Semaphore mutex = new Semaphore(1);
        CyclicBarrier barrier = new CyclicBarrier(3, resetTrains);
        Train t1 = new Train(train1, (byte) 1, mutex, msg, buttonStart, barrier);
        Train t2 = new Train(train2, (byte) 2, mutex, msg, buttonStart, barrier);
        Train t3 = new Train(train3, (byte) 3, mutex, msg, buttonStart, barrier);

        t1.start();
        t2.start();
        t3.start();

        //Always update the JScrollPane of the JtextArea
        DefaultCaret caret = (DefaultCaret) msg.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }//GEN-LAST:event_buttonStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trail.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trail.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trail.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trail.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton buttonStart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea msg;
    private javax.swing.JLabel track1;
    private javax.swing.JLabel track2;
    private javax.swing.JLabel track3;
    private static javax.swing.JLabel train1;
    private static javax.swing.JLabel train2;
    private static javax.swing.JLabel train3;
    // End of variables declaration//GEN-END:variables
}
