/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trail;

import java.util.concurrent.Semaphore;

/**
 *
 * @author danx_
 */
public class Trail extends javax.swing.JFrame {

    /**
     * Creates new form Trail
     */
    public Trail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        train2 = new javax.swing.JLabel();
        train1 = new javax.swing.JLabel();
        track1 = new javax.swing.JLabel();
        track2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(200, 100));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 600));

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 600));
        jPanel1.setLayout(null);

        train2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trail/Train2.png"))); // NOI18N
        train2.setAlignmentY(0.0F);
        jPanel1.add(train2);
        train2.setBounds(1150, 410, 100, 100);

        train1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trail/Train1.png"))); // NOI18N
        train1.setAlignmentY(0.0F);
        jPanel1.add(train1);
        train1.setBounds(50, 410, 100, 100);

        track1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trail/TrainTrack.png"))); // NOI18N
        track1.setAlignmentY(0.0F);
        track1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(track1);
        track1.setBounds(50, 50, 600, 460);

        track2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trail/TrainTrack.png"))); // NOI18N
        track2.setAlignmentY(0.0F);
        track2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(track2);
        track2.setBounds(650, 50, 600, 460);

        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jButton1.setText("Go!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 530, 100, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Semaphore mutex = new Semaphore(1);
        Train t1 = new Train(train1, true, mutex);
        Train t2 = new Train(train2, false, mutex);
        
        t1.reset();
        t2.reset();
        
        //t1.a = true;
        //t2.a = true;
        
        t1.start();
        t2.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel track1;
    private javax.swing.JLabel track2;
    private static javax.swing.JLabel train1;
    private static javax.swing.JLabel train2;
    // End of variables declaration//GEN-END:variables
}
